In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/layoffs.csv')

df.head()

,Company,Location_HQ,Industry,Laid_Off_Count,Date,Source,Funds_Raised,Stage,Date_Added,Country,Percentage,List_of_Employees_Laid_Off
0,Oda,Oslo,Food,150.0,2024-06-05,https://techcrunch.com/2024/06/05/softbank-bac...,691.0,Unknown,2024-06-05 18:01:25,Norway,NaN,Unknown
1,Pagaya,Tel Aviv,Finance,100.0,2024-06-05,https://www.calcalistech.com/ctechnews/article...,2000.0,Post-IPO,2024-06-05 23:11:24,Israel,0.20,Unknown
2,Aleph Farms,Tel Aviv,Food,30.0,2024-06-05,https://www.calcalistech.com/ctechnews/article...,119.0,Unknown,2024-06-05 23:13:43,Israel,0.30,Unknown
3,MoonPay,Dover,Crypto,30.0,2024-06-05,https://www.theblock.co/post/298638/moonpay-la...,651.0,Unknown,2024-06-05 23:12:47,United States,0.10,Unknown
4,Yext,New York City,Marketing,NaN,2024-06-05,https://www.investing.com/news/economy-news/ye...,117.0,Post-IPO,2024-06-05 18:02:40,United States,0.12,Unknown

In [3]:
df.shape

(3642, 12)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3642 entries, 0 to 3641
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Company                     3642 non-null   str
 1   Location_HQ                 3642 non-null   str
 2   Industry                    3642 non-null   str
 3   Laid_Off_Count              2389 non-null   float64
 4   Date                        3642 non-null   str
 5   Source                      3642 non-null   str
 6   Funds_Raised                3252 non-null   float64
 7   Stage                       3642 non-null   str
 8   Date_Added                  3642 non-null   str
 9   Country                     3642 non-null   str
 10  Percentage                  2342 non-null   float64
 11  List_of_Employees_Laid_Off  3642 non-null   str
dtypes: float64(3), str(9)
memory usage: 951.6 KB

In [5]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Company,3642,2596,Google,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Location_HQ,3642,240,SF Bay Area,905,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Industry,3642,31,Finance,451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Laid_Off_Count,2389.0,NaN,NaN,NaN,257.926329,829.432277,3.0,40.0,80.0,181.0,14000.0
Date,3642,825,2020-04-02,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Source,3642,3407,Internal memo,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Funds_Raised,3252.0,NaN,NaN,NaN,798.569494,4758.393161,0.0,51.0,166.0,469.25,121900.0
Stage,3642,16,Post-IPO,768,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date_Added,3642,3603,2020-03-28 20:52:49,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,3642,63,United States,2369,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Percentage,2342.0,NaN,NaN,NaN,0.281216,0.287294,0.0,0.1,0.17,0.3,1.0
List_of_Employees_Laid_Off,3642,48,Unknown,3595,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df['Date'] = pd.to_datetime(df['Date'])

In [11]:
df = df.dropna(subset=['Laid_Off_Count'])
df['Laid_Off_Count'] = df['Laid_Off_Count'].fillna(0)

In [12]:
df['Company'] = df['Company'].str.strip()
df['Industry'] = df['Industry'].str.strip()
df['Country'] = df['Country'].str.strip()

In [13]:
df = df.drop_duplicates()